### ISSUE TITLE
HEREDOC must be enabled.

### ISSUE THREAD

**Issue by f** [sdogruyol/tren#2]
@sdogruyol You removed HEREDOCs but these are required to prevent quote injections.

If you write
```sql
-- name: get_user(name)
select * from users where name = "{{name}}"
```

Now it will generate a code

```crystal
def get_user(name)
  "select * from users where name = "{{name}}""
end
```

As you can see it's an invalid SQL query. But if you use HEREDOC you don't have to escape quotes in SQL file. That's why I put HEREDOCs.

I offer reverting HEREDOC.

**Comment by sdogruyol** [comment]
I wasn't aware of this issue.

However in postgresql it's already invalid to do something like

```sql
select * from users where name = "serdar"
```

WDYT?
