### ISSUE TITLE
Multiple Queries with multiline sql queries

### ISSUE THREAD

**Issue by sdogruyol** [sdogruyol/tren#4]
Since https://github.com/sdogruyol/tren/blob/master/src/reader.cr#L31 makes the assumption of having the next query at next line this won't work.

```sql
-- name: multiline()
SELECT * FROM users
LIMIT 1
```

It'll just grab ```SELECT * FROM users``` and then ignore rest.

**Comment by sdogruyol** [comment]
//cc @alpert @f

**Comment by crossonrose** [comment]
Why you Alpert?
