### ISSUE TITLE
Escape by default

### ISSUE THREAD

**Issue by RX14** [sdogruyol/tren#8]
Doesn't it make more sense to escape SQL inputs by default, then use `!` for unescaped values? Currently, if you accidentally miss the `!`, you're vulnerable to SQL injection. If you make it the other way around, if you accidentally leave off `!`, your queries don't work, which you will pick up immediately in testing.

**Comment by sdogruyol** [comment]
@RX14 this is also what i thought at first. 

@f said that this prevents query composition.

**Comment by RX14** [comment]
Query composition simply becomes `{{! query }}` instead of `{{ query }}`.

**Comment by f** [comment]
I'm going to convert it now :)

**Comment by f** [comment]
@RX14 @sdogruyol Please see https://github.com/sdogruyol/tren/pull/9

**Comment by sdogruyol** [comment]
Closed via https://github.com/sdogruyol/tren/pull/9. Thanks @RX14

**Comment by crossonrose** [comment]
Going to work not.
